/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Alex
 */
public class ViewMenuPrincipal extends javax.swing.JFrame {

    ViewMantenimientoCliente viewMantenimientoCliente = new ViewMantenimientoCliente();
    ViewReserva viewReserva = new ViewReserva();
    ViewAcercaDe viewAcercaDe = new ViewAcercaDe();

    /**
     * Creates new form Principal
     */
    public ViewMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmenuArchivo = new javax.swing.JMenu();
        menuItemSalir = new javax.swing.JMenuItem();
        jmenuReserva = new javax.swing.JMenu();
        jmenuMantenimiento = new javax.swing.JMenu();
        menuItemMantenimientoCliente = new javax.swing.JMenuItem();
        jmenuAyuda = new javax.swing.JMenu();
        menuItemAcercaDe = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Programa");
        setPreferredSize(new java.awt.Dimension(800, 600));

        escritorio.setAutoscrolls(true);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );

        jmenuArchivo.setText("Archivo");

        menuItemSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        menuItemSalir.setText("Salir");
        menuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSalirActionPerformed(evt);
            }
        });
        jmenuArchivo.add(menuItemSalir);

        jMenuBar1.add(jmenuArchivo);

        jmenuReserva.setText("Reserva");
        jmenuReserva.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jmenuReservaMenuSelected(evt);
            }
        });
        jmenuReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuReservaActionPerformed(evt);
            }
        });
        jMenuBar1.add(jmenuReserva);

        jmenuMantenimiento.setText("Mantenimiento");

        menuItemMantenimientoCliente.setText("Cliente");
        menuItemMantenimientoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemMantenimientoClienteActionPerformed(evt);
            }
        });
        jmenuMantenimiento.add(menuItemMantenimientoCliente);

        jMenuBar1.add(jmenuMantenimiento);

        jmenuAyuda.setText("Ayuda");

        menuItemAcercaDe.setText("Acerca de");
        menuItemAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAcercaDeActionPerformed(evt);
            }
        });
        jmenuAyuda.add(menuItemAcercaDe);

        jMenuBar1.add(jmenuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSalirActionPerformed
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemSalirActionPerformed

    private void menuItemAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAcercaDeActionPerformed

        if (viewAcercaDe.isVisible()) {
            viewAcercaDe.setAlwaysOnTop(true);
        } else {
            viewAcercaDe.setVisible(true);
            viewAcercaDe.setLocationRelativeTo(null);
        }
    }//GEN-LAST:event_menuItemAcercaDeActionPerformed

    private void menuItemMantenimientoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemMantenimientoClienteActionPerformed
        // TODO add your handling code here:

        if (viewMantenimientoCliente.isShowing()) {
            viewMantenimientoCliente.setVisible(true);
            viewMantenimientoCliente.toFront();
        } else {
            escritorio.add(viewMantenimientoCliente);
            viewMantenimientoCliente.show();
        }
    }//GEN-LAST:event_menuItemMantenimientoClienteActionPerformed

    private void jmenuReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuReservaActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jmenuReservaActionPerformed

    private void jmenuReservaMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jmenuReservaMenuSelected
        // TODO add your handling code here:
        if (viewReserva.isShowing()) {
            viewReserva.setVisible(true);
            viewReserva.toFront();
        } else {
            escritorio.add(viewReserva);
            viewReserva.show();
        }

    }//GEN-LAST:event_jmenuReservaMenuSelected

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu jmenuArchivo;
    private javax.swing.JMenu jmenuAyuda;
    private javax.swing.JMenu jmenuMantenimiento;
    private javax.swing.JMenu jmenuReserva;
    private javax.swing.JMenuItem menuItemAcercaDe;
    private javax.swing.JMenuItem menuItemMantenimientoCliente;
    private javax.swing.JMenuItem menuItemSalir;
    // End of variables declaration//GEN-END:variables
}
